# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 知白说
subtitle: '一名互联网民工的潦草记录'
description: '记录我日常生活和学习的地方'
keywords:
author: 知白
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://zermzhang.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: '/articles/'
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: next
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

navbar:
  blog_title: 潦草小窝
  menu:
    - { key: '文章', link: '/articles/', icon: 'iconfont icon-book' }
    - {
        key: '归档',
        icon: 'iconfont icon-books',
        submenu: [
            { key: '分类', link: '/categories/' },
            { key: '时间线', link: '/archives/' },
            { key: '标签', link: '/tags/' }
        ]
    }
    - { key: '关于', link: '/about/', icon: 'iconfont icon-user-fill' }

index:
  slogan:
    enable: true
    text: 这里是我的记录自留地
  post_url_target: _self
  banner_img: /images/bg/waterfalls-gd6a1535f5_1920.jpeg

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "prismjs"
    prismjs:
      style: "default"
      preprocess: true

about:
  avatar: /images/avatar/avatar.PNG
  name: 知白
  into: 一名互联网码农的潦草记录
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/ZermZhang', tip: 'Github' }
    - { class: 'iconfont icon-zhihu-fill', link: 'https://www.zhihu.com/people/zhang-zhen-91-77', tip: 'Zhihu'}
    - { class: 'iconfont icon-note', link: 'https://blog.csdn.net/zhang371312', tip: 'CSDN'}
  banner_img: /images/bg/river-7190415_1280.jpeg

tag:
  banner_img: /images/bg/beach-1751455__340.webp

archive:
  banner_img: /images/bg/hintersee-3601004__340.webp

category:
  banner_img: /images/bg/trees-6207925__480.webp

post:
  math:
    enable: true
    specific: true
    engine: mathjax
  
  comments:
    enable: true
    type: valine

valine:
  appId: S8eucA2DyD8F5gpiLDyALbGN-MdYXbMMI
  appKey: 33iTB6VQqNpGX7g5TInAtUtq
  path: window.location.pathname
  placeholder:
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: false
  serverURLs: 'https://s8euca2d.api.lncldglobal.com'
  emojiCDN:
  emojiMaps:
  enableQQ: false

static_prefix:
  mathjax: https://lib.baomitu.com/mathjax/3.2.1/

favicon: /images/avatar/avatar.PNG
apple_touch_icon: /images/avatar/avatar.PNG